# Generated by Django 5.1.7 on 2025-03-27 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=250)),
                ('nivel_dificuldade', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='basico', max_length=13)),
                ('categoria', models.CharField(max_length=40)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.perfil')),
            ],
        ),
    ]
