# Generated by Django 5.1.7 on 2025-03-31 20:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_alter_playlist_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=11)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='uploads/videos/thumbnails', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('titulo', models.CharField(max_length=150)),
                ('canal', models.CharField(max_length=150)),
                ('nivel_dificuldade', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='basico', max_length=13)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.playlist')),
            ],
        ),
    ]
