# Generated by Django 5.1.7 on 2025-04-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='nivel_dificuldade',
        ),
        migrations.RemoveField(
            model_name='video',
            name='playlist',
        ),
        migrations.AddField(
            model_name='playlist',
            name='videos',
            field=models.ManyToManyField(blank=True, to='plataforma.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
