# Generated by Django 5.1.7 on 2025-04-01 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_remove_video_nivel_dificuldade_remove_video_playlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_dificuldade', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='basico', max_length=13)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.playlist')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.video')),
            ],
            options={
                'unique_together': {('playlist', 'video')},
            },
        ),
    ]
