# Generated by Django 5.1.7 on 2025-04-02 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_alter_video_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=250)),
                ('avaliacao_positiva', models.IntegerField(default=0)),
                ('avaliacao_negativa', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.playlistvideo')),
            ],
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='videos',
        ),
        migrations.CreateModel(
            name='PerguntaAlternativas',
            fields=[
                ('pergunta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plataforma.pergunta')),
                ('alternativa1', models.CharField(max_length=100)),
                ('alternativa2', models.CharField(max_length=100)),
                ('alternativa3', models.CharField(max_length=100)),
                ('alternativa4', models.CharField(max_length=100)),
                ('alternativa_correta', models.IntegerField()),
            ],
            bases=('plataforma.pergunta',),
        ),
        migrations.CreateModel(
            name='PerguntaVerdadeiroFalso',
            fields=[
                ('pergunta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plataforma.pergunta')),
                ('resposta', models.BooleanField()),
            ],
            bases=('plataforma.pergunta',),
        ),
    ]
