# Generated by Django 5.1.7 on 2025-04-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_progressovideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressovideo',
            name='data_conclusao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
