# Generated by Django 5.1.7 on 2025-04-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0009_alter_progressovideo_data_conclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressovideo',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
