# Generated by Django 5.1.7 on 2025-04-15 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0012_perfil_cursos_concluidos_perfil_cursos_criados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.FileField(blank=True, default='img/perfil/default.png', null=True, upload_to='img/perfil', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
