# Generated by Django 5.1.7 on 2025-04-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0013_perfil_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntaalternativas',
            name='nivel_dificuldade',
            field=models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='basico', max_length=13),
        ),
    ]
