# Generated by Django 5.1.7 on 2025-04-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0014_perguntaalternativas_nivel_dificuldade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perguntaalternativas',
            name='nivel_dificuldade',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='nivel_dificuldade',
            field=models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='basico', max_length=13),
        ),
    ]
