# Generated by Django 5.1.7 on 2025-04-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0015_remove_perguntaalternativas_nivel_dificuldade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progressopergunta',
            old_name='resposta_correta',
            new_name='acertou',
        ),
    ]
