# Generated by Django 5.1.7 on 2025-04-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0016_rename_resposta_correta_progressopergunta_acertou'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='energia',
        ),
        migrations.AddField(
            model_name='perfil',
            name='vida',
            field=models.IntegerField(default=10),
        ),
    ]
