# Generated by Django 5.1.7 on 2025-05-07 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0017_remove_perfil_energia_perfil_vida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressoPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_completa', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.playlist')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'playlist')},
            },
        ),
    ]
