# Generated by Django 5.1.7 on 2025-05-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0018_progressoplaylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressoplaylist',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
