# Generated by Django 5.1.7 on 2025-05-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0019_alter_progressoplaylist_data_conclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='valor_progresso',
            field=models.IntegerField(default=0),
        ),
    ]
