# Generated by Django 5.1.7 on 2025-05-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0020_playlist_valor_progresso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='valor_progresso',
        ),
        migrations.AddField(
            model_name='progressoplaylist',
            name='valor_progresso',
            field=models.IntegerField(default=0),
        ),
    ]
