# Generated by Django 5.1.7 on 2025-05-13 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0021_remove_playlist_valor_progresso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressoplaylist',
            name='valor_progresso',
        ),
    ]
