# Generated by Django 5.1.7 on 2025-05-13 21:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0022_remove_progressoplaylist_valor_progresso'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ultima_recarga_vida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='perfil',
            name='vida_maxima',
            field=models.IntegerField(default=10),
        ),
    ]
